import Head from 'next/head'
import Image from 'next/Image'

import ArticlesList from '../components/ArticlesList'

export default function Home({articlesList}) {
  console.log(articlesList)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ArticlesList articlesList={articlesList} />

    </div>
  )
}

// { partnersList.map((provider) =>

export async function getStaticProps() {
    
  const articlesList = await fetch(`http://localhost:8055/items/articles`)
    .then( response => response.json())

  return {
      props: {
        articlesList: articlesList.data
      }
  }
}